#!/bin/bash

set -e

if id -u evqueue >/dev/null 2>&1; then
        deluser --quiet evqueue
fi

if service --status-all | grep -Fq 'rsyslog'; then
	service rsyslog restart
fi

#DEBHELPER#

# Force clean exit to prevent broken pacakge
exit 0
