#!/bin/bash

set -e

if [ "$1" = "configure" ]; then
	if ! getent group evqueue > /dev/null 2>&1 ; then
		addgroup --system --quiet evqueue
	fi
	
	if ! getent passwd evqueue > /dev/null 2>&1 ; then
		adduser --quiet --system --disabled-login --ingroup evqueue --home /var/run/evqueue/ --no-create-home evqueue
	fi
	
	chown -R evqueue:evqueue /usr/share/evqueue-core
	
	. /usr/share/debconf/confmodule
	db_get evqueue-core/hostname
	sed --in-place -e "s/#\?[ ]*mysql.host[ ]*=.*/mysql.host=$RET/" /etc/evqueue.conf

	db_get evqueue-core/user
	sed --in-place -e "s/#\?[ ]*mysql.user[ ]*=.*/mysql.user=$RET/" /etc/evqueue.conf

	db_get evqueue-core/password
	sed --in-place -e "s/#\?[ ]*mysql.password[ ]*=.*/mysql.password=$RET/" /etc/evqueue.conf

	db_get evqueue-core/database
	sed --in-place -e "s/#\?[ ]*mysql.database[ ]*=.*/mysql.database=$RET/" /etc/evqueue.conf
	
	service rsyslog restart
fi

#DEBHELPER#
