#!/bin/bash

if [ "$1" = "configure" ]; then
	if ! getent group evqueue > /dev/null 2>&1 ; then
		addgroup --system --quiet evqueue
	fi
	
	if ! getent passwd evqueue > /dev/null 2>&1 ; then
		adduser --quiet --system --disabled-login --ingroup evqueue --home /var/run/evqueue/ --no-create-home evqueue
	fi
	
	chown -R evqueue:evqueue /usr/share/evqueue-core
	
	/etc/init.d/rsyslog restart
	
	exit 0
fi