.TH "EVQUEUE_AGENT" 8 "2016-07-11" "evQueue agent" "evqueue"

.SH NAME
evqueue_agent \- evQueue agent
.SH "SYNOPSIS"
.PP
\fBevqueue_agent\fR <command> [parameters]*
.SH "DESCRIPTION"
.PP
Enable additional logging functionalities when evQueue tasks are launched through SSH.
.PP
This should normally be used only by evQueue core daemon when launching remote tasks.
.SH SEE ALSO
.BR http://www.evqueue.net/

